export enum ToolFunctionEnum {
  DECISION_MAKING_SUPPORT = 1,
  MODELING_VISIONING = 2,
  MONITORING_DATA_COLLECTION = 3,
  OUTREACH_INTERACTION_INFLUENCE = 4,
  TEACHING_TRAINING_TOOLKITS = 5,
  UNDERSTANDING_ASSESSING = 6,
}
