import { MigrationInterface, QueryRunner } from 'typeorm';
import { TemplateEnum } from '../../domain/shared/auxiliar/template/enum/template.enum';

export class UpdateTemplateHyperLink1758510659334
  implements MigrationInterface
{
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`UPDATE \`sec_template\`
        SET \`template\` = '<!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>OICR</title>
                <style>
                body {
                    font-family: Arial, sans-serif;
                    color: #333;
                    line-height: 1.5;
                    font-size: 15px;
                }
                .footer {
                    margin-top: 20px;
                    font-size: 13px;
                    color: #666;
                }
                </style>
            </head>
            <body>
                <p>Dear SPRM team,</p>
                <p>A new preliminary OICR submission has been created in STAR. Please find the details below:</p>
                <ul style="font-family: Arial, sans-serif; font-size: 15px; color: #333; padding-left: 40px;">
                <li><b>Request Number:</b> {{result_code}}</li>
                <li><b>OICR Title:</b> {{result_title}}</li>
                <li><b>Associated Project:</b> <a href="{{contract_link}}" target="_blank">{{contract_code}} – {{contract_description}}</a></li>
                <li><b>Principal Investigator:</b> {{principal_investigator}}</li>
                <li><b>Primary Lever:</b> {{primary_lever}}</li>
                <li><b>Main Contact Person:</b> {{main_contact_person}}</li>
                <li><b>Request Date:</b> {{cration_date}}</li>
                <li><b>Description:</b> {{oicr_description}}</li>
                </ul>

                <p><i>This notification is automatically generated by STAR to ensure timely follow-up according to the MEL process.</i></p>
                <p>Kind regards,</p>
                <p><b>STAR System Notification</b></p>
                
                <div class="footer">
                <p><i>Please do not reply to this email, as this mailbox is not monitored.</i></p>
                </div>
            </body>
            </html>'
        WHERE \`name\` = '${TemplateEnum.OICR_NOTIFICATION_CREATED}';`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`UPDATE \`sec_template\`
        SET \`template\` = '<!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>OICR</title>
                <style>
                body {
                    font-family: Arial, sans-serif;
                    color: #333;
                    line-height: 1.5;
                    font-size: 15px;
                }
                .footer {
                    margin-top: 20px;
                    font-size: 13px;
                    color: #666;
                }
                </style>
            </head>
            <body>
                <p>Dear SPRM team,</p>
                <p>A new preliminary OICR submission has been created in STAR. Please find the details below:</p>
                <ul style="font-family: Arial, sans-serif; font-size: 15px; color: #333; padding-left: 40px;">
                <li><b>Request Number:</b> {{result_code}}</li>
                <li><b>OICR Title:</b> {{result_title}}</li>
                <li><b>Associated Project:</b> {{contract_code}} – {{contract_description}}</li>
                <li><b>Principal Investigator:</b> {{principal_investigator}}</li>
                <li><b>Primary Lever:</b> {{primary_lever}}</li>
                <li><b>Main Contact Person:</b> {{main_contact_person}}</li>
                <li><b>Request Date:</b> {{cration_date}}</li>
                <li><b>Description:</b> {{oicr_description}}</li>
                </ul>

                <p>You can directly access the preliminary OICR submission through STAR: {{oicr_link}}</p>

                <p><i>This notification is automatically generated by STAR to ensure timely follow-up according to the MEL process.</i></p>
                <p>Kind regards,</p>
                <p><b>STAR System Notification</b></p>
                
                <div class="footer">
                <p><i>Please do not reply to this email, as this mailbox is not monitored.</i></p>
                </div>
            </body>
            </html>'
        WHERE \`name\` = '${TemplateEnum.OICR_NOTIFICATION_CREATED}';`);
  }
}
