import { MigrationInterface, QueryRunner } from 'typeorm';
import { TemplateEnum } from '../../domain/shared/auxiliar/template/enum/template.enum';

export class InsertOicrTemplates1759951810292 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(` insert into \`sec_template\` (\`name\`, \`template\` ) values ('${TemplateEnum.OICR_APPROVED}', '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OICR Approval Notification</title>
  </head>
  <body>
    <p>Dear {{requester_by}},</p>
    <p>
      Your OICR submission has been reviewed and approved. Please find the
      details below:
    </p>
    <br />
    <ul>
      <li>OICR No.: {{oicr_number}}</li>
      <li>OICR Title: {{title}}</li>
      <li>Assigned MEL Regional Expert: {{mel_expert_name}}</li>
      <li>SharePoint Folder Link: {{sharepoint_url}}</li>
      <li>Reviewer: {{reviewed_by}}</li>
      <li>Decision Date: {{decision_date}}</li>
    </ul>
    <p>
      Your OICR development will continue with PISA support. Please use the
      assigned folder link for documentation and next steps.
    </p>
    <p>You can access your OICR submission directly through STAR: {{url}}</p>
    <p>
      This notification is automatically generated by STAR to ensure timely
      follow-up according to the MEL process.
    </p>
    <br />
    <p>Kind regards,</p>
    <p>STAR System Notification</p>
    <p>
      <i
        >Please do not reply to this email, as this mailbox is not monitored.</i
      >
    </p>
  </body>
</html>'), ('${TemplateEnum.OICR_POSTPONE}', '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OICR Postponement Notification</title>
  </head>
  <body>
    <p>Dear {{requester_by}},</p>
    <p>
      Your OICR submission has been reviewed and is currently marked as
      Postponed. Please find the details below:
    </p>
    <br />
    <ul>
      <li>OICR Title: {{title}}</li>
      <li>Reviewer: {{reviewed_by}}</li>
      <li>Decision Date: {{decision_date}}</li>
      <li>Reviewer’s Justification: {{justification}}</li>
    </ul>
    <p>
      Your OICR will not proceed further this year but will be reconsidered in
      the following reporting cycle, based on its evolution and relevance.
    </p>
    <p>You can access your OICR submission directly through STAR: {{url}}</p>
    <p>
      This notification is automatically generated by STAR to ensure timely
      follow-up according to the MEL process.
    </p>
    <br />
    <p>Kind regards,</p>
    <p>STAR System Notification</p>
    <p>
      <i
        >Please do not reply to this email, as this mailbox is not monitored.</i
      >
    </p>
  </body>
</html>'), ('${TemplateEnum.OICR_REJECTED}', '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OICR Rejection Notification</title>
  </head>
  <body>
    <p>Dear {{requester_by}},</p>
    <p>
      Your OICR submission has been reviewed and is marked as Rejected. Please
      find the details below:
    </p>
    <br />

    <ul>
      <li>OICR Title: {{title}}</li>
      <li>Reviewer: {{reviewed_by}}</li>
      <li>Decision Date: {{decision_date}}</li>
      <li>Reason for Rejection: {{justification}}</li>
    </ul>

    <p>
      At this time, no further action is required. If applicable, you may
      consider submitting a new request in the future, taking into account the
      feedback provided.
    </p>

    <p>You can access your OICR submission directly through STAR: {{url}}</p>

    <p>
      This notification is automatically generated by STAR to ensure timely
      follow-up according to the MEL process.
    </p>
    <br />
    <p>Kind regards,</p>
    <p>STAR System Notification</p>
    <p>
      <i
        >Please do not reply to this email, as this mailbox is not monitored.</i
      >
    </p>
  </body>
</html>
')`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM \`sec_template\` WHERE name IN ('${TemplateEnum.OICR_APPROVED}', '${TemplateEnum.OICR_POSTPONE}', '${TemplateEnum.OICR_REJECTED}')`,
    );
  }
}
