import { MigrationInterface, QueryRunner } from 'typeorm';
import { TemplateEnum } from '../../domain/shared/auxiliar/template/enum/template.enum';

export class UpdateOicrTemplate1760712418098 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`UPDATE sec_template SET name = '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OICR Approval Notification</title>
  </head>
  <body>
    <p>Dear {{requester_by}},</p>
    <p>
      Your OICR submission has been reviewed and <b>approved</b>. Please find
      the details below:
    </p>
    <br />
    <ul>
      <li><b>OICR No.:</b> {{oicr_number}}</li>
      <li><b>OICR Title:</b> {{title}}</li>
      <li><b>Assigned MEL Regional Expert:</b> {{mel_expert_name}}</li>
      <li><b>SharePoint Folder Link:</b> {{sharepoint_url}}</li>
      <li><b>Reviewer:</b> {{reviewed_by}}</li>
      <li><b>Decision Date:</b> {{decision_date}}</li>
    </ul>
    <p>
      Your OICR development will continue with PISA support. Please use the
      assigned folder link for documentation and next steps.
    </p>
    <p>You can access your OICR submission directly through STAR: {{url}}</p>
    <p>
      This notification is automatically generated by STAR to ensure timely
      follow-up according to the MEL process.
    </p>
    <br />
    <p>Kind regards,</p>
    <p>STAR System Notification</p>
    <p>
      <i
        >Please do not reply to this email, as this mailbox is not monitored.</i
      >
    </p>
  </body>
</html>
' WHERE name = '${TemplateEnum.OICR_APPROVED}';`);

    await queryRunner.query(`UPDATE sec_template SET name = '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OICR Postponement Notification</title>
  </head>
  <body>
    <p>Dear {{requester_by}},</p>
    <p>
      Your OICR submission has been reviewed and is currently marked as
      <b>Postponed</b>. Please find the details below:
    </p>
    <br />
    <ul>
      <li><b>OICR No.:</b> {{oicr_number}}</li>
      <li><b>OICR Title:</b> {{title}}</li>
      <li><b>Reviewer:</b> {{reviewed_by}}</li>
      <li><b>Decision Date:</b> {{decision_date}}</li>
      <li><b>Reviewer’s Justification:</b> {{justification}}</li>
    </ul>
    <p>
      Your OICR will not proceed further this year but will be
      <b>reconsidered in the following reporting cycle</b>, based on its
      evolution and relevance.
    </p>
    <p>You can access your OICR submission directly through STAR: {{url}}</p>
    <p>
      This notification is automatically generated by STAR to ensure timely
      follow-up according to the MEL process.
    </p>
    <br />
    <p>Kind regards,</p>
    <p>STAR System Notification</p>
    <p>
      <i
        >Please do not reply to this email, as this mailbox is not monitored.</i
      >
    </p>
  </body>
</html>
' WHERE name = '${TemplateEnum.OICR_POSTPONE}';`);

    await queryRunner.query(`UPDATE sec_template SET name = '<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OICR Rejection Notification</title>
  </head>
  <body>
    <p>Dear {{requester_by}},</p>
    <p>
      Your OICR submission has been reviewed and is marked as <b>Rejected</b>.
      Please find the details below:
    </p>
    <br />

    <ul>
      <li><b>OICR Title:</b> {{title}}</li>
      <li><b>Reviewer:</b> {{reviewed_by}}</li>
      <li><b>Decision Date:</b> {{decision_date}}</li>
      <li><b>Reason for Rejection:</b> {{justification}}</li>
    </ul>

    <p>
      At this time, no further action is required. If applicable, you may
      consider submitting a new request in the future, taking into account the
      feedback provided.
    </p>

    <p>You can access your OICR submission directly through STAR: {{url}}</p>

    <p>
      This notification is automatically generated by STAR to ensure timely
      follow-up according to the MEL process.
    </p>
    <br />
    <p>Kind regards,</p>
    <p>STAR System Notification</p>
    <p>
      <i
        >Please do not reply to this email, as this mailbox is not monitored.</i
      >
    </p>
  </body>
</html>
' WHERE name = '${TemplateEnum.OICR_REJECTED}';`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM \`sec_template\` WHERE name IN ('${TemplateEnum.OICR_APPROVED}', '${TemplateEnum.OICR_POSTPONE}', '${TemplateEnum.OICR_REJECTED}')`,
    );
  }
}
