export type ModalName =
  | 'createResult'
  | 'submitResult'
  | 'requestPartner'
  | 'askForHelp'
  | 'createOicrResult'
  | 'resultInformation'
  | 'addContactPerson'
  | 'selectLinkedResults'
  | 'editEnvironmentVariable'
  | 'editPrompt'
  | 'projectGroundingSetup'
  | 'portfolioManagement'
  | 'assignPiDelegate'
  | 'piDelegateHistory'
  // @akili-spec changes/profile-simulation — R-IMP-007, design §2.2/§6
  | 'simulateProfile'
  | 'portfolio2025LeverSdgs'
  | 'portfolio2026SdgTargets'
  | 'poolFundingHelp';
