export type ModalName =
  | 'createResult'
  | 'submitResult'
  | 'requestPartner'
  | 'askForHelp'
  | 'createOicrResult'
  | 'resultInformation'
  | 'addContactPerson'
  | 'selectLinkedResults'
  | 'editEnvironmentVariable'
  | 'editPrompt'
  | 'projectGroundingSetup'
  | 'portfolioManagement'
  | 'portfolio2025LeverSdgs'
  | 'portfolio2026SdgTargets';
