export enum AppConfigKey {
  ARI_CLARISA_API_KEY = 'ARI_CLARISA_API_KEY',
  ARI_CLARISA_PROJECTS_PHASE = 'ARI_CLARISA_PROJECTS_PHASE',
  PORTFOLIO_2026_SDG_TARGET_CODES = 'PORTFOLIO_2026_SDG_TARGET_CODES',
}
