export enum AppConfigKey {
  ARI_CLARISA_API_KEY = 'ARI_CLARISA_API_KEY',
  ARI_CLARISA_PROJECTS_PHASE = 'ARI_CLARISA_PROJECTS_PHASE',
  POOL_FUNDING_SECTION_ENABLED = 'POOL_FUNDING.SECTION.ENABLED',
  POOL_FUNDING_PRMS_SYNC_BUTTON_ENABLED = 'POOL_FUNDING.PRMS_SYNC_BUTTON.ENABLED',
}
