export const APPLICATION_CONFIGURATION_KEY = {
  DATE_FORMAT: 'date-format',
  BULK_UPLOAD_EMBED_URL: 'BULK_UPLOAD.EMBED_INFO.URL',
  POOL_FUNDING_SECTION_ENABLED: 'POOL_FUNDING.SECTION.ENABLED',
  POOL_FUNDING_PRMS_SYNC_BUTTON_ENABLED: 'POOL_FUNDING.PRMS_SYNC_BUTTON.ENABLED'
} as const;
